smartclean/smartclean.github.io

docs/reports_actions_edit.md
docs/reports_actions_run.md
docs/reports_actions_view_share.md

Minor readability and UX update:
In the 3 Report Actions subpages 
- Goal: Make consistent and add help text where insufficient info.

Update report actions (Make consistent, add help text)

---

docs/audits.md
docs/reports.md
docs/reports_faqs.md
docs/workorders.md

1. Add FAQs for Reports service (and provide link from the Reports page)
2. Update versions of other services (as instructed)
3. Minor updates to Improve content and navigation

Add FAQs for Reports, Update service versions.

---

docs/sensorPayloads.md

Add basic payload and description for WD and AQ in sensorPayloads page.

Describe payload for AQ and WD (subject to review)

---

docs/sensorPayloads.md

1. Improve Consumable docs, remove attribute "d"
2. Fix data alignment issues
3. Fix a spelling error
Merging this Pull Request will close 2 issues: #25 and #26

Fixes and improvements

---

docs/sensorPayloads.md
docs/sensorPayloads_examples.md

1. Add requested improvements to the page. (Further Details in the commit message: https://github.com/smartclean/smartclean.github.io/commit/4aba66cb8681b05140856dc62232bfcd6e2aa2ee)
2. Add subpage for examples to sensorPayloads page

Sensor Payloads - improvements and examples

---

docs/sensorPayloads_examples.md

Fixed the capital letters like before.
Make the page title smaller

Fix capital letters in headings, make page title smaller

---

docs/realsense_sensors.md

Commit: https://github.com/smartclean/smartclean.github.io/commit/fbb4b9c788506cd3c7e0023e6e97e2159b0a5e77

Fix error in a sentence

---

docs/realsense_sensors.md

Update sentence for firmware versions

---

docs/sensorPayloads_examples.md
docs/vcs_aq.md
docs/vcs_bin.md
docs/vcs_cmd.md
docs/vcs_pc.md
docs/vcs_wd.md

1. Add a goal statement
2. Update how this solution works (details of steps and reset conditions)
3. Add how to activate the solution (1 line explanation)
4. Highlight words in bold and italics where found necessary.

Describe PC solution better, add device info link to sensor payload examples, improve content

---

docs/api_main.md
docs/releaseNotesMain-2022-03-05.md
docs/releaseNotesMain.md
docs/sensorPayloads_examples.md

Update 1:
Release notes: 
[Fix 1 spelling error and improve 1 sentence structure]
Update 2: 
SensorPayloads:
Update title names of the devices

Minor proposed Improvements

---

docs/api_main.md

Updates added to API (Postman collection) page.

Add proposed changes, and steps on usage

---

docs/api_main.md

During review a minor sentence structure confusion identified.
Screenshot attached.
This has now been fixed

Improve sentence structure (remove a confusing overlap)

---

docs/realsense_sensor_data.md
docs/realsense_sensor_data_aq.md

Description: See title of 2 commits.

Add proposed changes.

---

docs/api_main.md
docs/releaseNotesMain-2022-03-19.md

See the 2 commits titles below.

Update API page. Update release notes with this info and HMAC signing

---

docs/api_main.md
docs/realsense_sensor_data_bin.md
docs/realsense_sensor_data_cmd.md
docs/releaseNotesMain-2022-04-09.md

Please review the content before merging.

Update 1) data payload (CMD / Bin - d / full value), 2) API (improvements), Add release notes

---

docs/releaseNotesMain-2022-04-16.md
docs/releaseNotesMain-2022-04-23.md

Navigation order attribute updated for the previous release notes page.

Latest release notes

---

docs/releaseNotesMain-2022-04-23.md
docs/releaseNotesMain-2022-04-30.md

1. Make the links clickable
2. Improve 1 sentence

Added latest release notes, minor improvements.

---

docs/realsense_sensor_data_pc.md
docs/releaseNotesMain-2022-04-30.md
docs/releaseNotesMain-2022-05-07.md

In Sensor Payload Examples for type: PC / UM,
type of value of "count" and "out_count" inside "v" of the data payload has been updated to float number from previously incorrect string type.

Add Release notes, minor update in sensor payload example for PC/UM

---

docs/api_main.md

Required information added under the Authentication section.

Add steps for basic and HMAC auth in Postman, under authentication

---

docs/releaseNotesMain-2022-05-14.md

Received content added with minor (language) edits.
1 enhancement point added for DataHandler service.

Add latest release notes.

---

docs/releaseNotesMain-2022-05-28.md

Provided content has been added.

Add release notes page - latest

---

docs/realsense_sensor_data.md
docs/realsense_sensor_data_aq.md
docs/realsense_sensor_data_pc.md

Refer to title of each commit below for the summary.

Improvements to Sensor Data payload

---

docs/multi-tenant-db.md

[Add page describing multi-tenant db under Matrix Event Bus](https://github.com/smartclean/smartclean.github.io/commit/2f68c9380b3acf67de675309b13e700c607048c9)
Note: This PR includes updates from a previous pull request: #72

Add the page with details.

---

docs/dedicated-db.md

- Change word: multi-tenant to dedicated
[Add note about multi-tenanted data access (mentioned in diagram)](https://github.com/smartclean/smartclean.github.io/commit/3fdbe8ff74287cff46cf59b4024ef5bad1e13e4a)
[Renamed the file from multi-tenant-db to dedicated-db](https://github.com/smartclean/smartclean.github.io/commit/48c78d709b273dedee7f8c4be7cf4cab43d4112d)

Update From multi-tenant to dedicated

---

docs/releaseNotesMain-2022-06-11.md

Fixed date in title,
Moved enhancement below the features.

Update for Release notes

---

docs/releaseNotesMain-2022-06-25.md
docs/vcs_settings.md

[Summarize configurable settings in table with default values](https://github.com/smartclean/smartclean.github.io/commit/f5491ae4b9e9d9e2705c94b9ca6c8f291a8b6136)

Latest Release Notes, table for default values of settings in VCS

---

docs/api_main.md
docs/vcs.md

(a) VCS page: Add new section on Smart decisions...
(b) API page: Update section: Authentication
Diagrams shared have been added.
Refer to commits below for each update.

Update with sections: (a) VCS - Smart decisions (b) API - Auth mechanisms

---

docs/integrations.md

Different options available have been summarised
Further improvements will be applied gradually.
**Review of the content is recommended**
After review, this PR will be converted from Draft to Ready for merging.
This PR includes the previous PR: #78

Integration mechanisms

---

docs/integrations.md
docs/integrations_db.md
docs/integrations_push.md
docs/integrations_sdk.md
docs/integrations_web.md

Improve structure of integrations

---

docs/integrations_db.md
docs/integrations_push.md
docs/integrations_sdk.md
docs/integrations_web.md
docs/realsense_main.md

For summary of changes, refer to to commits listed below.

Improvements from review

---

docs/releaseNotesMain-2022-07-02.md
docs/releaseNotesMain-2022-07-23.md

2 Pre-release candidates have been added.

Release notes for 23 July

---

docs/api_main.md

Postman collection has following updates:
1. Service folder: Work Orders renamed to Workforce
2. Add folder for: Get assigned Tasks (calls Workforce: LastNTasks for desired entity)
- 1 request for following entities:
- Property
- Building
- Zone
- Seat
- default time range: 24 hours for each entity
- custom time range: accept StartTime and EndTime for each entity.
Documentation of collection is updated with this change.

API: Import link to Postman collection updated.

---

docs/iam_sso.md
docs/iam_sso_ms.md

Draft of proposed content added:
- Single Sign On added under IAM
- Sub page for Single Sign On (with Microsoft Azure AD) added under this page.
Subject to review and revisions.

SSO under IAM + SSO with MS Azure AD.

---

docs/iam_sso.md

[SSO-enable TOC, remove width of process flow image](https://github.com/smartclean/smartclean.github.io/commit/b91d6da812afe04abe1336cf3051a1a94aeabec7)

SSO-enable TOC, remove width of process flow image

---

docs/iam_sso.md
docs/iam_sso_ms.md

Minor improvement to Page format for better readability.

Required updates and fixes + minor improvements.

---

docs/iam_sso.md
docs/iam_sso_ms.md

Improvements include:
1. Minor issue in 1 sentence 
2. Update title of page for SSO using Microsoft Azure AD
General improvements in certain places content to make it more clear.

Proposed and observed improvements.

---

docs/iam.md
docs/iam_sso.md
docs/iam_sso_ms.md

1. Latest 2 commits contain minor observed improvements for clarity of content.
2. Update Latest Stable Version for IAM.
Note: No new content added or any content removed.

(a) IAM: Update Version (b) IAM-SSO: observed improvements

---

docs/realsense_sensor_data_fd.md

This update is ready for review.

Feedback device data: Update format and example, add more notes.

---

docs/releaseNotesMain-2022-09-17.md

Includes minor update to 2 statements which were not pushed before.

Fix date in title

---

docs/releaseNotesMain-2022-10-01.md

Subject to review and approval

Start draft for latest release notes

---

docs/integrations_ui.md

Listed down names of these example widgets  taken from the sample dashboard for SC Demo Project: Gallen (along with a 1 line explanation)

Define example widgets in a dashboard

---

docs/releaseNotesMain-2022-10-15.md

4/6 recommended points included and explained.
2/6 points could not be included due to following reasons (per point)
1. Atlassian Status Page for Matrix: This was already included in the previous release notes that are available.
2. ESG widgets for embeddable BI dashboards - insufficient details given. Need more clarification or link to some documentation for readers of release notes to find out more.

Add latest release notes

---

docs/releaseNotesMain-2022-10-15.md

1. Additional ESG widgets
2. Service desk
Improve 1 existing statement for options available in incidents metrics report
Fix page property: navigation order (previously matched an existing sub page)

Add 2 enhancements, Fix 1 statement page nav_order

---

docs/integrations_ui.md
docs/releaseNotesMain-2022-10-15.md

Examples and screenshots for the same added in relevant sections.

Add info about new ESG widgets

---

docs/releaseNotesMain-2022-10-15.md

Add matrix kiosk app as new feature/release section.
- Added the details shared.

Add matrix kiosk app in latest release notes

---

docs/vcs_aq_settings.md

- New category represents the alert based on max threshold for ammonia value
- Note regarding the pre-requisite activation has been added.
- Device level setting: Max ammonia threshold has been explained under this new category
- Note regarding the 2 categories and the default category has also been added.

Add new category for AQ solution in settings.

---

docs/integrations_ui.md
docs/integrations_ui_faq.md

1. Outcome section shortened to remove 2 unecessary points
- As these points can be covered under steps for access
2. Elaborate the limited lifetime aspect under this section to specify the quota of active sessions per project and improve the formatting.

Embeddable BI - Improve sections: Outcome, Steps for access

---

docs/releaseNotes/releaseNotes-2022/releaseNotesMain-2022-10-29.md

Start tasks & incidents on HouseKeeping mobile App without need to start a shift.

Add new candidate to enhancements

---

docs/integrations_ui_faq.md
docs/releaseNotes/releaseNotes-2022/releaseNotesMain-2022-11-12.md

Thanks to hello-error for reporting the unwanted lines remaining in the release notes page
And also for reporting invalid points in question about security in the embeddable-ui page.

Remove invalid points in 2 pages, improve 1 point in release notes.

---

docs/realsense_data_push.md
docs/realsense_hw_sec_flash_enc.md
docs/realsense_hw_secure_casing.md
docs/realsense_hw_secure_interface.md
docs/realsense_hw_security.md
docs/realsense_hw_security_bootload.md

Further details have been added in Sub pages.
Basic contents are covered and links provided for further information.

Add page group on hardware security (under RealSense)

---

docs/realsense_hw_secure_casing.md

**Page Group:** _RealSense_
**Page:** _Hardware Security_
**Sub Page:** _Secure Casing_
**Section:** _Examples_ 
For each image added under this section,
1. Fix the links (previously images would not display as these links were from images in OneDrive cloud)
2. Add heading to each image (for better understanding)
3. Set width to 530px (height is by default, auto-adjusted)

RealSense>Hardware Security>Secure Casing: To each image, Fix link, add heading and set width.

---

docs/data_policies.md
docs/privacy.md

This content was added as a draft due to a requirement given around mid of last year to include a privacy policy and data policies in the online documentation.
Refer to first commit on 14 July 2022 (below)
The content was not reviewed.
Keeping the content in view, in case it is applicable in future
- Since the status of this requirement is unknown, no further actions being taken.

New page for privacy and for Data policies.

---

docs/realsense_hw_security_androidsecurity.md

Hi need this for SGBC certification. Please expedite, thanks!

Android security portion added

---

docs/realsense_sensor_data_aq.md
docs/realsense_sensors.md

For more information, refer to individual commits

Updates and improvements for AQ Device data 

---

docs/realsense_sensor_data_aq.md

Table for IAQ index classification did not render properly in the docs portal. Alternative has been released

Replace table with link to file and source.

---

docs/realsense_sensor_data_occ.md
docs/realsense_sensor_data_tilt.md

Update completed and reviewed for publishing online.
Device categories added:
1. Occupancy
2. Tree tilt

Add 2 new device data pages under realsense

---

docs/realsense_sensor_data_th.md

Type added: TH (Temperature - Humidity)

Add new device data page under RealSense
